apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-pv-claim
  namespace: ingress-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi